# Generated by Django 6.1.1 on 2026-10-07 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_short_table_names'),
        ('users', '0004_short_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, db_table='filter_preference_tags', related_name='filter_preferences', to='tags.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filter_preferences',
            },
        ),
        migrations.CreateModel(
            name='FilterPreferenceWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('filter_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='users.filterpreference')),
            ],
            options={
                'db_table': 'filter_preference_weekdays',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('filter_preference', 'weekday'), name='filter_preference_weekday_unique'), models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='filter_preference_weekday_iso')],
            },
        ),
    ]
