# Generated by Django 6.1.1 on 2026-10-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_filter_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterpreference',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
