# Generated by Django 6.1.1 on 2026-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_filter_preference_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('undisclosed', 'Do not want to tell')], default='undisclosed', max_length=11),
        ),
    ]
