# Generated by Django 6.1.1 on 2026-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adult_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
