# Generated by Django 6.1.1 on 2026-10-01 22:38

import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_datetimes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CREATE EXTENSION vector; tags' embedding migration depends on this one
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='event_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
