# Generated by Django 6.1.1 on 2026-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='connections_applied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
