# Generated by Django 6.1.1 on 2026-10-04 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='occasion_users', related_name='occasions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='occasion',
            table='occasions',
        ),
    ]
