# Generated by Django 6.1.1 on 2026-10-04 17:40

import apps.occasions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_occasionuser_is_active_cancelled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.occasions.models.image_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='occasions.occasion')),
            ],
            options={
                'db_table': 'occasion_images',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('occasion', 'order'), name='occasion_image_order_unique'), models.CheckConstraint(condition=models.Q(('order__lte', 3)), name='occasion_image_order_range', violation_error_message='The order must be between 0 and 3.')],
            },
        ),
    ]
