# Generated by Django 6.1.1 on 2026-10-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0005_occasion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
