# Generated by Django 6.1.1 on 2026-10-08 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0006_occasion_description'),
        ('tags', '0004_short_table_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20160)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_occasion_templates', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, db_table='occasion_template_tags', related_name='occasion_templates', to='tags.tag')),
            ],
            options={
                'db_table': 'occasion_templates',
                'ordering': ['name', 'id'],
            },
        ),
    ]
