# Generated by Django 6.1.1 on 2026-10-08 17:49

import apps.occasions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0007_occasion_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionTemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.occasions.models.template_image_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='occasions.occasiontemplate')),
            ],
            options={
                'db_table': 'occasion_template_images',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'order'), name='template_image_order_unique'), models.CheckConstraint(condition=models.Q(('order__lte', 3)), name='template_image_order_range', violation_error_message='The order must be between 0 and 3.')],
            },
        ),
    ]
