# Generated by Django 6.1.1 on 2026-10-01 22:38

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_embedding'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='tag_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
