# Generated by Django 6.1.1 on 2026-10-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='events',
            new_name='occasions',
        ),
    ]
