# Generated by Django 6.1.1 on 2026-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_short_table_names'),
        ('tags', '0003_rename_events_field_to_occasions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='occasions',
            field=models.ManyToManyField(blank=True, db_table='tag_occasions', related_name='tags', to='occasions.occasion'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
