# Generated by Django 6.1.1 on 2026-10-02 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=0)),
                ('shared_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_low', '-strength'], name='connection_low_strength_idx'), models.Index(fields=['user_high', '-strength'], name='connection_high_strength_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='connection_users_ordered'), models.UniqueConstraint(fields=('user_low', 'user_high'), name='connection_pair_unique')],
            },
        ),
    ]
