# Generated by Django 6.1.1 on 2026-10-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='shared_events',
            new_name='shared_occasions',
        ),
    ]
