# Generated by Django 6.1.1 on 2026-10-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_rename_shared_events_to_shared_occasions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connection',
            table='connections',
        ),
    ]
